language: java
jdk:
  - openjdk8

addons:
  sonarcloud:
    organization: "ferzerkerx-github"
    token:
      secure: "quYJTCcqYMnbRb4Iv6ZsyogWGeUQl0YDpUKVJt/9iSwjfUB4Y/LUMR0e7KRoFSFT3Ce3rH4WzL+Z5e10iDraS1WF1LnmSzTFxBe9cJ5f4GVakCn5MnW3jQbmmE8SDh4CtALKoXJ5cRpMfMwklW9766uYFyzy2S4eHs22cbmrXlaJ+jrCsvdSH5xKljliC0WeTsKzRWx8kDh1xQz/hiakfGf0iJKopaAZvp38W+jzzbxxhlbMgSSWcnpfqdjCi8xrwt3GH5/Ik89osX+bWdxYJhMrK6mNa+xAwjiWKLGILckZoabcmH07JPl5OsiXlHofHK7l2y3sxo4pWThyaIc3DB6bc+0PqmpW9/mSjTq+PK09V9gjoIJ0/7tl82pduZdv7D2HnD4dihTzYkH7oKqVLcCb0m5vRgFMIF7gHnqvzAQVBCxaAneteBWQ/D59dXCVv3/sMr1/+fHw6e6WOcsTeislZKUCJSCKItU23OqFHd4Q5PW+fKS5Y5bq3Zzojg/Y2J8LbmBaBaDxqXvxs5NXPgu+iy2z4jYozSqTpwGnQB+UFTLvYQYOWqVMO4bj0qm3s2e6cjQxBvEXGqnLnQoIepnrYqu0BfhnFqq4DoRxe3BJhVj1WKvtm4bbvpH2w9u5/LOscB4u8ge7zgcc9bOphF4IpzlaFyPKsTujRbUR+Sw="
env:
  secure: "khP/A1Kn6NJLae8AA33OfvTfWcRpdVdd7A6aAlNKSH0h7XY+Z1n9XC0AHaYkTYRFVeBzPbXDl6faTT8Pw4oKARaDKfzSs7IwBf1qK5BQ790qDXRbdVLCb70SMmJY1Rg2etyt0PlmxKbnGGSxvemPAg30OZ36kkjFaa/jiyucGtUdhtAKK68wTrlyWJJzuNkf9sZs7UX78Jw3QpsQl/XwcTu8dBtFeSlUiIdxv2m470n4jV+q+2UbxMfZOQmFP49gIC/HAv4cZ7/qD3JOnVx7Xgp3Ro+A0H3pSUOWacg8CTTwZMbyDzzEfLF/Q+W+yGP0n+wRV/QJxjmPXhH+7ZDiYmQ+26sxWtYYgidmG5+10bNZUoKETmzfvO6CaqPelBFFpascvRvnzYTANQGSowSHdO92ur9fgWneZ6eCAjawF7SJZRsNR+nwcd5Mc1ohIqv/R9pIegkqVz44PY1zkATnsdtWEN5okihKhSplixVPrbeu7LD0xPmE9hUXp3OyJczkfLd9+UOvDre35SuVnc3QCXDNU99dOwzJHY+T4U26T0HNP6RXKl0s5lVELMiOIJhOM5Ya0t2FpPqF9OL9fd4dB3ZsPu65vjnLOmsGzXCpEyWgsrckSPfLNOXg47eSYOvFxZWVfuWff7/Y6SbiBO8u1f7Y5TxnZv1lXFecvUmLT20="

install:
  - "mvn clean compile"
  - "npm install -g snyk"

script:
  - "mvn install sonar:sonar"

after_success:
  - snyk monitor
