language: java
jdk:
  - oraclejdk8

addons:
  sonarcloud:
    organization: "ferzerkerx-github"
    token:
      secure: "fGGLwoeTRHcWr2KzUOZhSVndwZ9LxTZ64+e5X2soUu6SK5hkZgE7TYoD7ks6aEWPtpEwtAeUxvUicjKZ8ZKbSp6ag4TfBc5x4YexNdYRf0Uw71E9wrMg+XFtj1A2Z7jHZCZgDwYeUZxEtG3elfNytLhiEtNarXh4Gp76apqL6RHHsWX5afx3vwdDfaDIKwQ3UGQ6vrd3Gr3+gN7QhqqARmNKmdGRkvZeUdB5ZEi9oujOsf7RoqErXaCtAuTYhciJYCwkTJ2HRrS5su+X87wupJa+aYBMkIX7zyvp4Cc3fa6qPAYR+GGEiyBVSk7Lrs/N5DQxtGcZIZZ+qHf4daywFhyhObwHMhCFHoZIVB2HOZcmnrifxQpIufSnQ1llaM1HnymPPJus+1DyD3bH6bVTFKov4gtKTvd/c+cyVIKlga+i5+YRrjwue6FKNgrONs+ARBU0evzDXiviq5mDMc+YQDCIe8OYp70haeKHdyYV/hg6W7ZRP56I2tJ0PYgqnaaax1U6UZQPBsD47OIoZJriTSMsYNP7NocoLOI/wY9aow6VbyKXwEglCQsEfsSA6gQmSX6ZqBIwN7LVwYXp4ZieCjo3B2ud5ioXK8B8ndmKHWkdxfEXFMiKSWwLAJrsTfjHJkNg4LSG3uJ7UV2qqV6OibeibapZR+Ap4wZp115SRgE="

env:
  secure: "khP/A1Kn6NJLae8AA33OfvTfWcRpdVdd7A6aAlNKSH0h7XY+Z1n9XC0AHaYkTYRFVeBzPbXDl6faTT8Pw4oKARaDKfzSs7IwBf1qK5BQ790qDXRbdVLCb70SMmJY1Rg2etyt0PlmxKbnGGSxvemPAg30OZ36kkjFaa/jiyucGtUdhtAKK68wTrlyWJJzuNkf9sZs7UX78Jw3QpsQl/XwcTu8dBtFeSlUiIdxv2m470n4jV+q+2UbxMfZOQmFP49gIC/HAv4cZ7/qD3JOnVx7Xgp3Ro+A0H3pSUOWacg8CTTwZMbyDzzEfLF/Q+W+yGP0n+wRV/QJxjmPXhH+7ZDiYmQ+26sxWtYYgidmG5+10bNZUoKETmzfvO6CaqPelBFFpascvRvnzYTANQGSowSHdO92ur9fgWneZ6eCAjawF7SJZRsNR+nwcd5Mc1ohIqv/R9pIegkqVz44PY1zkATnsdtWEN5okihKhSplixVPrbeu7LD0xPmE9hUXp3OyJczkfLd9+UOvDre35SuVnc3QCXDNU99dOwzJHY+T4U26T0HNP6RXKl0s5lVELMiOIJhOM5Ya0t2FpPqF9OL9fd4dB3ZsPu65vjnLOmsGzXCpEyWgsrckSPfLNOXg47eSYOvFxZWVfuWff7/Y6SbiBO8u1f7Y5TxnZv1lXFecvUmLT20="

install:
  - "mvn clean compile"
  - "npm install -g snyk"

script:
  - "mvn install sonar:sonar"
  - "snyk test"

after_success:
  - snyk monitor